### ISSUE TITLE
Moving System Is Slightly Laggy

### ISSUE THREAD

**Issue by mastari** [eoriont/TheStoryRealms#2]
I am not not positive what is making it laggy because right now it could either be something in the rendering process or something else in the code that I am not aware of. It would be awesome if you could fix this. Thanks!

**Comment by eoriont** [comment]
On it. I might need some time though, and it might not be perfect. Computers have a lot of RAM and GPU, so if I make the methods more efficient, It might not make a difference. I'll try though.

**Comment by eoriont** [comment]
I finished debugging the problem: The blocks were being rendered off the screen. Now you just have to pull the repo onto your computer. Also, I remembered that you did some work, so don't forget to push it to github! Thanks, you can close this issue now.

**Comment by mastari** [comment]
@eoriont - I am still seeing some lag, so I reopened the issue. The lag meaning everything jitters around. It gets hard to look at after awhile and I strongly think this should be fixed for the quality of movement for the game. Thanks for all your work on refining the game! -mastari

**Comment by eoriont** [comment]
Hi mastari, I just fixed a ton of lag, apparently the game doesn't like to load images from files a thousand times a second. Hopefully this is good for you because else, I don't know what to do. Also, I need my textures soon if you want to release the game!
