### ISSUE TITLE
Widgets SpriteSheet!

### ISSUE THREAD

**Issue by eoriont** [eoriont/TheStoryRealms#3]
Hello, I need a spritesheet for widgets and buttons. I have already made one for them, so you can pull the repo and get it. What this needs to have in it is:

1: mouse normal
2: mouse about-to-click (the finger in this case)
3: mouse click

4: button neutral
5: button held-over
6: button clicked

NOTE: The buttons do NOT have to be 16x16. PLEASE MAKE THEM BIGGER THEN THAT. They can take up multiple squares, but please, try to use the space efficiently, like putting the buttons in the top left corner of the squares.

Also, you can resize the template as much as you want. just be sure to make the template a square!

**Comment by mastari** [comment]
I will get right to it after I have finished the Player Sprite Sheet

**Comment by eoriont** [comment]
Actually, you should make this your first priority because I need to make the start menu, and to do that, I need buttons and other pictures.

**Comment by mastari** [comment]
I will make some widgets now, and also, can you come on Skype because my code is still broken and I cannot test any of the textures or sprite sheets I create... Thanks @eoriont .

**Comment by mastari** [comment]
So, just to be clear, I can have the button art take up **_two_** boxes?

**Comment by eoriont** [comment]
Yes. I see that you have made the spritesheet, and you did a great job. The one thing more that I need is the button-clicked texture. It would be great if you could get this done soon. Thanks!

**Comment by mastari** [comment]
Done!
