### ISSUE TITLE
My Code Keeps Breaking...

### ISSUE THREAD

**Issue by mastari** [eoriont/TheStoryRealms#4]
Hey Eli,
 When ever I start the code it does not open up the JFrame and it just gives this error:
Error:(15, 38) java: cannot find symbol
  symbol:   variable Map
  location: class com.ohmaststudios.generator.Map

I know you have fixed this before, but it still is giving me a bad time. Any thoughts on this? I have already tried debugging

**Comment by eoriont** [comment]
Yeah, I can tell where that's going. So I deleted the map class and it will throw an error if you use it any more. So you might have to delete one of the imports or the map class to fix it. Please let me know if you need any help fixing it.

**Comment by mastari** [comment]
I need help fixing it @eoriont

**Comment by mastari** [comment]
**UPDATE:** I just fixed it, for some reason before when I deleted it, it did not work.
Thanks! -mastari
